[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_IS_NETLIFY = "true"

# Use our custom CSS handling plugin
[[plugins]]
  package = "./netlify/plugins/netlify-plugin-nextjs-css"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
